### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AlexanderFabisch** [cau-se/ARCHES-PiCar-X#5]
* I'd suggest to link the documentation (https://cau-se.github.io/ARCHES-PiCar-X/) directly in the project description (right top: project website).
* When I click on "Get started now" I get a 404 error.

openjournals/joss-reviews/issues/7179

**Comment by AlexanderBarbie** [comment]
sorry, first time using the github pages stuff and changed the structure several times.

**Comment by AlexanderFabisch** [comment]
> I'd suggest to link the documentation (https://cau-se.github.io/ARCHES-PiCar-X/) directly in the project description (right top: project website).

What about this? Just a recommendation, but you didn't comment on it.

**Comment by AlexanderBarbie** [comment]
had to google it first. :) 
was wondering all the time how to link the github pages on the front page of the repo
