### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by mrsonandrade** [cau-se/ARCHES-PiCar-X#8]
**Describe the bug**
Everything was fine following the "Getting Started". Thus, as I don't have the physical car, I followed to “Explore -> Example for replacing the physical twin with a digital twin prototype  -> Option 3: Only the Digital Twin starts a simulation”. Thus, for this line:

`docker compose -f docker-compose-dtsim.yml build`

I got this error during the building:
`service “motor-emulator_right-dt” depends on undefined service “picarx-dt”: invalid compose project`

**To Reproduce**
1. After success with the [Getting Started](https://cau-se.github.io/ARCHES-PiCar-X/getting_started.html), go to [Replace the Physical Twin with a Digital Twin Prototype and Connect it to a Digital Twin](https://cau-se.github.io/ARCHES-PiCar-X/digitaltwins/dtp.html).
2. Follow the [Option 3](https://cau-se.github.io/ARCHES-PiCar-X/digitaltwins/dtp.html#option3).
3. When you give `docker compose -f docker-compose-dtsim.yml build`.
4. You have the following error `service “motor-emulator_right-dt” depends on undefined service “picarx-dt”: invalid compose project`.

**Additional context**
Before all steps above I tested the [Let the ARCHES PiCar-X Drive](https://cau-se.github.io/ARCHES-PiCar-X/getting_started.html#let-the-arches-picar-x-drive) and everything was working great.

https://github.com/openjournals/joss-reviews/issues/7179

**Comment by AlexanderBarbie** [comment]
Great news that the installation worked. :)

I fixed the errors in the compose files and they build and start on my systems now. Should have tested this better after refactoring...

Since you were already on the explore page: I adjusted the documentation for the setup with the DTP including Gazebo and the DT including Gazebo (option 1). I started it on the same system, but was never thinking about the fact that they both share the same I2C device and i cannot create a second I2C-stub device on my system. I will elaborate this part in the documentation at the weekend.

**Comment by danielskatz** [comment]
@mrsonandrade - does this now work for you?

**Comment by AlexanderBarbie** [comment]
sooo... I played around a bit more and added an additional docker compose file to enable the execution of the digital twin prototype and a digital twin as counterpart with running gazebo for both. Furthermore, I reverted changes on the mosquitto config, sometimes the mqtt server did not start properly on my windows system. Moreover, I added an environment variable to set the mqtt server ip, this should be easier than setting it in the compose file. I will adjust the documentation today when I am back from work.

**Comment by danielskatz** [comment]
👋 @mrsonandrade - How does this look now?

**Comment by mrsonandrade** [comment]
@danielskatz sorry for the late reply.

@AlexanderBarbie thank you for the effort! I have two points:
- When I click on “Explore” at the end of the “Getting Started” page, it goes to the “Digital Twin Concept” page (not to the Explore one, as expected).
- By following the new steps [here](https://cau-se.github.io/ARCHES-PiCar-X/explore/dtps/dtpdt.html#start-digital-twin-prototype-and-digital-twin-with-separate-gazebo-simulation), when I try to register the additional address space (0x15) by using `sudo modprobe i2c-stub chip_addr=[0x14, 0x15]`, I get the following: `modprobe: ERROR: could not insert ‘i2c_stub’: Invalid argument`. The command works fine if I have only one address, e.g. `sudo modprobe i2c-stub chip_addr=0x14`. What should I do?

**Comment by AlexanderBarbie** [comment]
please try `sudo modprobe i2c-stub chip_addr=0x14,0x15`
I would add a list of values in general with [], but looks like i2c-stub wants a list of values comma separated.

**Comment by mrsonandrade** [comment]
Great! Everything is working now!
