### ISSUE TITLE
enhance the paper

### ISSUE THREAD

**Issue by AlexanderBarbie** [cau-se/ARCHES-PiCar-X#9]
Based on the comments of @AlexanderFabisch I already made modification to the paper but opened this issue to track the commits better.

>Software paper
Summary:
The summary could be improved: referring to

>>This paper presents a digital twin prototype of...

>What is a digital twin and why is it useful?

>>Our goal is to provide researchers and practitioners with an affordable and straightforward example to explore various concepts of digital twins.

>What are these concepts of digital twins? In which way can they be explored?

>>Moreover, this example can be used to explore all the concepts implemented in a previous project named ARCHES (Autonomous Robotic Networks to help Human Societies), which focused on monitoring and operating an underwater network of ocean observation systems

>Again, what are these concepts and how are we able to explore these with the picar?

>>One of the outcomes of this project was the ARCHES Digital Twin Framework

>Can you briefly describe what the ARCHES Digital Twin Framework does and why it is needed?

>A statement of need:
>>Digital twins are becoming increasingly relevant...

>Why are they becoming more relevant? Certainly they are useful in a way, but it is not clear to me.

>>Industrial Internet of Things and Industry 4.0

>I think these terms need references.

>Quality of writing:
>I think the structure could be improved. Here are two suggestions.
As I pointed out before it would be useful to point out which are the digital twin concepts from the ARCHES framework that should be demonstrated by this software and then point out how this is achieved in the following sections.
>The description of the Picar, CAD model, and Digital Twin could be one section. If the automated testing pipeline is one of the concepts to be demonstrated in the paper, then I would put it in another section with all the other concepts that the software is supposed to demonstrate.

https://github.com/openjournals/joss-reviews/issues/7179

**Comment by AlexanderBarbie** [comment]
@AlexanderFabisch sorry, took me a while because I have a lot of stuff to do.. but I finally revised the paper and tried to make it more concrete in the areas you highlighted. However, I'm already over the 1,000-word limit and would prefer not to write a third paper with the same definitions as in the two referenced ones. Instead, I've added more about the digital twin concept to the documentation.

**Comment by AlexanderFabisch** [comment]
Looks very good!

Just one more comment:  There is a typo in "possible sources of erros" -> errors

(I'd suggest to use a spell checker like aspell on the file to remove all typos that I missed.)

**Comment by AlexanderBarbie** [comment]
great suggestion, don't know why I haven't thought about a spell checker in vscode before..  found quite a lot!

**Comment by AlexanderBarbie** [comment]
@mrsonandrade I reopened this issue for discussion.

>I’m almost done with all the points on my list. My last point concerns the State of the field, which should be in the paper. Thus, are there other related packages? If yes, please, compare them. If not, I think it is valid to clarify this in the paper.

I added a related work section, but since I already exceeded the 1000 words, I only briefly discuss the differences. Is this okay for you?

**Comment by mrsonandrade** [comment]
@AlexanderBarbie - Excellent!
